### ISSUE TITLE
http in osmosis configuration after import (causes OsmosisRuntimeException)

### ISSUE THREAD

**Issue by VShkaberda** [Overv/openstreetmap-tile-server#129]
I just pull latest docker image (DIGEST `cacf034aa8fc`) and witness that `configuration.txt` contains `http` instead of `https`:
```
cat /var/lib/mod_tile/.osmosis/configuration.txt 
# The URL of the directory containing change files.
baseUrl=http://planet.openstreetmap.org/replication/minute

# Defines the maximum time interval in seconds to download in a single invocation.
# Setting to 0 disables this feature.
maxInterval = 3600
```
It was also the issue earlier. So I just manually fix the `configuration.txt` every time. Command I executed to import:
```
docker run \
    -e UPDATES=enabled \
    -v /home/osm/ukraine-latest.osm.pbf:/data.osm.pbf \
    -v /home/osm/ukraine.poly:/data.poly \
    -v openstreetmap-rendered-tiles:/var/lib/mod_tile \
    -v openstreetmap-data:/var/lib/postgresql/12/main \
    overv/openstreetmap-tile-server \
    import
```

**Comment by Overv** [comment]
It's definitely better to enforce https but is this actually causing a problem with functionality?

**Comment by VShkaberda** [comment]
Yes, osmosis fails to perform updates because of it. Content of `/var/log/tiles/osmosis.log` with error caused by `http` in `configuration.txt`:
<details><summary>osmosis.log</summary><p>

```
Apr 30, 2020 8:44:01 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Osmosis Version 0.46
Apr 30, 2020 8:44:01 PM org.java.plugin.registry.xml.ManifestParser <init>
INFO: got SAX parser factory - org.apache.xerces.jaxp.SAXParserFactoryImpl@72d818d1
Apr 30, 2020 8:44:01 PM org.java.plugin.registry.xml.PluginRegistryImpl configure
INFO: configured, stopOnError=false, isValidating=true
Apr 30, 2020 8:44:02 PM org.java.plugin.registry.xml.PluginRegistryImpl register
INFO: plug-in and fragment descriptors registered - 1
Apr 30, 2020 8:44:02 PM org.java.plugin.standard.StandardPluginManager activatePlugin
INFO: plug-in started - org.openstreetmap.osmosis.core.plugin.Core@0.46.0 (active/total: 1 of 1)
Apr 30, 2020 8:44:02 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Preparing pipeline.
Apr 30, 2020 8:44:02 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Launching pipeline execution.
Apr 30, 2020 8:44:02 PM org.openstreetmap.osmosis.core.Osmosis run
INFO: Pipeline executing, waiting for completion.
Apr 30, 2020 8:44:02 PM org.openstreetmap.osmosis.core.pipeline.common.ActiveTaskManager waitForCompletion
SEVERE: Thread for task 1-read-replication-interval failed
org.openstreetmap.osmosis.core.OsmosisRuntimeException: The replication state doesn't contain a timestamp property.
        at org.openstreetmap.osmosis.replication.common.ReplicationState.loadProperty(ReplicationState.java:65)
        at org.openstreetmap.osmosis.replication.common.ReplicationState.load(ReplicationState.java:78)
        at org.openstreetmap.osmosis.replication.common.ReplicationState.<init>(ReplicationState.java:59)
        at org.openstreetmap.osmosis.replication.common.ServerStateReader.getServerState(ServerStateReader.java:103)
        at org.openstreetmap.osmosis.replication.common.ServerStateReader.getServerState(ServerStateReader.java:46)
        at org.openstreetmap.osmosis.replication.v0_6.BaseReplicationDownloader.runImpl(BaseReplicationDownloader.java:257)
        at org.openstreetmap.osmosis.replication.v0_6.BaseReplicationDownloader.run(BaseReplicationDownloader.java:350)
        at java.base/java.lang.Thread.run(Thread.java:834)

Apr 30, 2020 8:44:02 PM org.openstreetmap.osmosis.core.Osmosis main
SEVERE: Execution aborted.
org.openstreetmap.osmosis.core.OsmosisRuntimeException: One or more tasks failed.
        at org.openstreetmap.osmosis.core.pipeline.common.Pipeline.waitForCompletion(Pipeline.java:146)
        at org.openstreetmap.osmosis.core.Osmosis.run(Osmosis.java:92)
        at org.openstreetmap.osmosis.core.Osmosis.main(Osmosis.java:37)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:330)
        at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:238)
        at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
        at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
        at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
```
</p></details>

**Comment by Overv** [comment]
I'm personally not familiar with the updating mechanism, so perhaps @stevo01 can pitch in here.

**Comment by ph1ll** [comment]
This seems to have been caused by a find/replace for http/https in https://github.com/Overv/openstreetmap-tile-server/commit/cc5b50b050a9e68f70b15dc2ed82aa1b5082de9a. I will do a quick PR now.
