### ISSUE TITLE
Import unable to reach naciscdn.org using latest Docker image

### ISSUE THREAD

**Issue by Kradenko** [Overv/openstreetmap-tile-server#211]
Hi,

I have tried several versions now of map imports and I get an error where it appears it is unable to reach a specific file that it wants to download:

urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='naciscdn.org', port=443): Max retries exceeded with url: /naturalearth/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4e8007e9a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

I am new to docker but I did login into bash and am able to reach the internet from within the container. So don't think it's a connectivity issue. Older versions of the docker image appears to work fine. 

Below is the whole error list. Thanks in advance!

Davin.

`INFO:root:Checking table ne_110m_admin_0_boundary_lines_land
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/connection.py", line 73, in create_connection
    for res in socket.getaddrinfo(host, port, family, socket.SOCK_STREAM):
  File "/usr/lib/python3.8/socket.py", line 918, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f4e8007e9a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='naciscdn.org', port=443): Max retries exceeded with url: /naturalearth/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4e8007e9a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/renderer/src/openstreetmap-carto/scripts/get-external-data.py", line 294, in <module>
    main()
  File "/home/renderer/src/openstreetmap-carto/scripts/get-external-data.py", line 230, in main
    download = s.get(source["url"], headers=headers)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 555, in get
    return self.request('GET', url, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='naciscdn.org', port=443): Max retries exceeded with url: /naturalearth/110m/cultural/ne_110m_admin_0_boundary_lines_land.zip (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f4e8007e9a0>: Failed to establish a new connection: [Errno -5] No address associated with hostname'))
+ touch /var/lib/mod_tile/planet-import-complete
+ service postgresql stop
 * Stopping PostgreSQL 12 database server
   ...done.
+ exit 0`

**Comment by mothlight** [comment]
Yes, I'm struggling with this as well.

I know that file is available at 
naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_boundary_lines_land.zip
but I don't know how to change the url in the docker.

**Comment by prih** [comment]
@mothlight https://github.com/gravitystorm/openstreetmap-carto/blob/master/external-data.yml#L65

https://github.com/Overv/openstreetmap-tile-server/blob/master/Dockerfile#L128

**Comment by prih** [comment]
@mothlight  like this #212
