### ISSUE TITLE
 Relation "icesheet_polygons" does not exist

### ISSUE THREAD

**Issue by bitmstr** [Overv/openstreetmap-tile-server#225]
I have completed and import and setup of tile servers several times, one or two of which were for the entire planet. I just attempted to setup the planet tile server again, however I got the following error in the run logs:

```
Mapnik LOG> 2021-11-12 23:24:28: warning: unable to find face-name 'Noto Sans Syriac Eastern Regular' in FontSet 'fontset-2'
Mapnik LOG> 2021-11-12 23:24:28: warning: unable to find face-name 'Noto Emoji Regular' in FontSet 'fontset-2'
Mapnik LOG> 2021-11-12 23:24:28: warning: unable to find face-name 'HanaMinA Regular' in FontSet 'fontset-2'
Mapnik LOG> 2021-11-12 23:24:28: warning: unable to find face-name 'HanaMinB Regular' in FontSet 'fontset-2'
Mapnik LOG> 2021-11-12 23:24:28: warning: unable to find face-name 'unifont Medium' in FontSet 'fontset-2'
Mapnik LOG> 2021-11-12 23:24:28: warning: unable to find face-name 'Noto Emoji Regular' in FontSet 'fontset-2'
Mapnik LOG> 2021-11-12 23:24:28: warning: unable to find face-name 'HanaMinA Regular' in FontSet 'fontset-2'
Mapnik LOG> 2021-11-12 23:24:28: warning: unable to find face-name 'HanaMinB Regular' in FontSet 'fontset-2'
Mapnik LOG> 2021-11-12 23:24:28: warning: unable to find face-name 'unifont Medium' in FontSet 'fontset-2'
renderd[143]: An error occurred while loading the map layer 'ajt': Postgis Plugin: ERROR:  relation "icesheet_polygons" does not exist
LINE 1: SELECT ST_SRID("way") AS srid FROM icesheet_polygons WHERE "...
                                           ^
in executeQuery Full sql was: 'SELECT ST_SRID("way") AS srid FROM icesheet_polygons WHERE "way" IS NOT NULL LIMIT 1;'
  encountered during parsing of layer 'icesheet-poly' in Layer at line 5911 of '/home/renderer/src/openstreetmap-carto/mapnik.xml'
renderd[143]: An error occurred while loading the map layer 'ajt': Postgis Plugin: ERROR:  relation "icesheet_polygons" does not exist
LINE 1: SELECT ST_SRID("way") AS srid FROM icesheet_polygons WHERE "...
                                           ^
in executeQuery Full sql was: 'SELECT ST_SRID("way") AS srid FROM icesheet_polygons WHERE "way" IS NOT NULL LIMIT 1;'
  encountered during parsing of layer 'icesheet-poly' in Layer at line 5911 of '/home/renderer/src/openstreetmap-carto/mapnik.xml'
renderd[143]: An error occurred while loading the map layer 'ajt': Postgis Plugin: ERROR:  relation "icesheet_polygons" does not exist
LINE 1: SELECT ST_SRID("way") AS srid FROM icesheet_polygons WHERE "...
                                           ^
in executeQuery Full sql was: 'SELECT ST_SRID("way") AS srid FROM icesheet_polygons WHERE "way" IS NOT NULL LIMIT 1;'
  encountered during parsing of layer 'icesheet-poly' in Layer at line 5911 of '/home/renderer/src/openstreetmap-carto/mapnik.xml'
renderd[143]: An error occurred while loading the map layer 'ajt': Postgis Plugin: ERROR:  relation "icesheet_polygons" does not exist
LINE 1: SELECT ST_SRID("way") AS srid FROM icesheet_polygons WHERE "...
                                           ^
in executeQuery Full sql was: 'SELECT ST_SRID("way") AS srid FROM icesheet_polygons WHERE "way" IS NOT NULL LIMIT 1;'
  encountered during parsing of layer 'icesheet-poly' in Layer at line 5911 of '/home/renderer/src/openstreetmap-carto/mapnik.xml'
```

This has happened several times in the past. Each time I just re-ran the import and run containers a couple of times and eventually it worked. However, my work-around is clearly unreliable and inefficient, especially when attempting to import the entire planet.

Can someone point me to a better solution? Why are the icesheet polygons unavailable?

Thanks in advance.

EDIT: This error occurs during run. The import error is listed in a comment below.

**Comment by Istador** [comment]
Interesting.

Normally the call to `get-external-data.py` during the `import` command should create the relation.
https://github.com/Overv/openstreetmap-tile-server/blob/705237446adacea44302692c8dfb0405dbfb2abd/run.sh#L81-L83

The external data is downloaded from [remote sources](https://github.com/gravitystorm/openstreetmap-carto/blob/v5.3.1/external-data.yml#L36-L47), so that part of the `import` and its output isn't that reliable.


Are there any error messages at the end of the `import`?

**Comment by bitmstr** [comment]
@Istador, good catch. That error was in the 'run' logs. There are several errors in the 'import' logs:

```
2021-11-12 23:23:51  Setting up table 'planet_osm_line'
2021-11-12 23:23:51  Setting up table 'planet_osm_polygon'
2021-11-12 23:23:51  Setting up table 'planet_osm_roads'
Processing: Node(117580k 1992.9k/s) Way(0k 0.00k/s) Relation(0 0.0/s)2021-11-12 23:24:50  ERROR: planet_osm_point - error on COPY: server closed the connection unexpectedly
        This probably means the server terminated abnormally
        before or while processing the request.

2021-11-12 23:24:50  ERROR: Data: 178117124     \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N    \N       \N      \N      tower   \N      \N      \N      \N      \N      \N      \N              0101000020110F00001C008688135C66C12A2B9C6915155241
178117128       \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      tower \N       \N      \N      \N      \N      \N      \N              0101000020110F0000F3A90909025D66C12E1C75C1B1125241
178117130       \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      tower \N       \N      \N      \N      \N      \N      \N              0101000020110F00001076836E3E5D66C1E091853FA4125241
178117183       \N      \N      \N      \N      \N      \
...
\N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      tower   \N      Anlage 336, Mast 3 ; 80 \N      \N      \N      \N      \N              0101000020110F00002EB51FB07B882F418906B8C41BD95741
183086078       \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      tower \N       Anlage 336, Mast 4 ; 81 \N      \N      \N      \N      \N              0101000020110F0000B4D8188DE2832F4181B3DFB1D7D85741
183086081       \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      \N      tower \N       Anlage 336, Mast 5 ; 82 \N      \N      \N      \N      \N              0101000020110F0000834C758B1D802F417DA071D79ED85741

2021-11-12 23:24:50  ERROR: DB copy thread failed: COPYing data to Postgresql.
+ sudo -u postgres psql -d gis -f /home/renderer/src/openstreetmap-carto/indexes.sql
psql: error: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?
+ sudo chown -R renderer: /home/renderer/src
+ sudo -E -u renderer python3 /home/renderer/src/openstreetmap-carto/scripts/get-external-data.py -c /home/renderer/src/openstreetmap-carto/external-data.yml -D /home/renderer/src/openstreetmap-carto/data
Traceback (most recent call last):
  File "/home/renderer/src/openstreetmap-carto/scripts/get-external-data.py", line 294, in <module>
    main()
  File "/home/renderer/src/openstreetmap-carto/scripts/get-external-data.py", line 192, in main
    psycopg2.connect(database=database,
  File "/usr/lib/python3/dist-packages/psycopg2/__init__.py", line 126, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not connect to server: No such file or directory
        Is the server running locally and accepting
        connections on Unix domain socket "/var/run/postgresql/.s.PGSQL.5432"?

+ touch /var/lib/mod_tile/planet-import-complete
+ service postgresql stop
 * Stopping PostgreSQL 12 database server
   ...done.
+ exit 0
```

It appears that something is interrupting the connection?

Thanks much

**Comment by Istador** [comment]
@Overv Can we maybe enable `set -e` in the `run.sh`, so that the script fails if any error occurs, instead of continuing to run and `exit 0` at the end (which seems like everything worked on first glance without consulting the logs)?

**Comment by Overv** [comment]
That sounds like a good idea. We should probably go for the full `set -euo pipefail` combo in that case.
