### ISSUE TITLE
Offline import

### ISSUE THREAD

**Issue by devinfra1** [Overv/openstreetmap-tile-server#378]
Hey,

I need to perform the import in a completely offline environment.

How can I provide the files
```
simplified-water-polygons-split-3857.zip
water-polygons-split-3857.zip
antarctica-icesheet-polygons-3857.zip
antarctica-icesheet-outlines-3857.zip
ne_110m_admin_0_boundary_lines_land.zip
```
In this disconnected environment?

**Comment by Istador** [comment]
Download them beforehand and use a local proxy?

**Comment by Istador** [comment]
- Call to `get-external-data.py`: https://github.com/Overv/openstreetmap-tile-server/blob/61270b8bffa9694c32442f989e14a9f6cf1d1aa3/run.sh#L118-L122
- [get-external-data.py](https://github.com/gravitystorm/openstreetmap-carto/blob/v5.4.0/scripts/get-external-data.py)
- [external-data.yml](https://github.com/gravitystorm/openstreetmap-carto/blob/v5.4.0/external-data.yml#L12)

**Comment by devinfra1** [comment]
Good morning,

After making some changes to the ptyhon script, so that it is reading my zip files locally and then unzipping, I am facing the following error log, which I am not able to resolve

```
error reading input file
+ '[' -e /data/tiles ']'
+ '[' -e /data/style/ ']'
+ '[' -e /data/database/ ']'
++ ls -A /data/style/
+ '[' '!' 'CARTOGRAPHY.md
CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
DOCKER.md
Dockerfile
Dockerfile.db
Dockerfile.import
INSTALL.md
LICENSE.txt
README.md
RELEASES.md
USECASES.md
data
docker-compose.yml
external-data.yml
indexes.sql
indexes.yml
mapnik.xml
openstreetmap-carto.lua
openstreetmap-carto.style
patterns
preview.png
project.mml
road-colors.yaml
scripts
style
symbols' ']'
+ '[' '!' -f /data/style/mapnik.xml ']'
+ '[' run == import ']'
+ '[' run == run ']'
+ rm -rf /tmp/httpd_shm.37 /tmp/httpd_shm_delay.37
+ '[' -f /nodes/flat_nodes.bin ']'
+ '[' -f /data/tiles/data.poly ']'
+ '[' -f /data/tiles/planet-import-complete ']'
+ '[' -f /data/database/planet-import-complete ']'
+ '[' -f /data/tiles/planet-import-complete ']'
+ '[' '' == enabled ']'
+ '[' '' == 1 ']'
+ service apache2 restart
 * Restarting Apache httpd web server apache2
[Fri Jun 23 15:58:02.700432 2023] [so:warn] [pid 208:tid 140686961756032] AH01574: module tile_module is already loaded, skipping
[Fri Jun 23 15:58:02.703962 2023] [tile:warn] [pid 208:tid 140686961756032] Could not determine host name of server to configure tile-json request. Using localhost instead
[Fri Jun 23 15:58:02.704114 2023] [tile:notice] [pid 208:tid 140686961756032] Loading tile config default at /tile/  for zooms 0 - 20 from tile directory /var/cache/renderd/tiles  with extension .png and mime type image/png
[Fri Jun 23 15:58:02.704368 2023] [tile:notice] [pid 208:tid 140686961756032] Loading tile config default at /tile/ for zooms 0 - 20 from tile directory /var/cache/renderd/tiles with extension .png and mime type image/png
[Fri Jun 23 15:58:02.704545 2023] [tile:notice] [pid 208:tid 140686961756032] Loading tile config default at /tile/  for zooms 0 - 20 from tile directory /var/cache/renderd/tiles  with extension .png and mime type image/png
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 10.0.90.47. Set the 'ServerName' directive globally to suppress this message
[Fri Jun 23 15:58:02.719012 2023] [so:warn] [pid 208:tid 140686961756032] AH01574: module tile_module is already loaded, skipping
   ...done.
+ sed -i -E 's/num_threads=[0-9]+/num_threads=4/g' /etc/renderd.conf
+ '[' disabled == enabled ']'
+ '[' disabled == 1 ']'
+ trap stop_handler SIGTERM
+ child=321
+ sudo -u renderer renderd -f -c /etc/renderd.conf
+ wait 321
** INFO: 15:58:03.755: Rendering daemon started
** INFO: 15:58:03.755: Initialising request_queue
** INFO: 15:58:03.756: Parsing section renderd
** INFO: 15:58:03.756: Parsing render section 0
** INFO: 15:58:03.756: Parsing section mapnik
** INFO: 15:58:03.756: Parsing section default
** INFO: 15:58:03.756: config renderd: unix socketname=/run/renderd/renderd.sock
** INFO: 15:58:03.756: config renderd: num_threads=4
** INFO: 15:58:03.756: config renderd: num_slaves=0
** INFO: 15:58:03.757: config renderd: tile_dir=/var/cache/renderd/tiles
** INFO: 15:58:03.757: config renderd: stats_file=/run/renderd/renderd.stats
** INFO: 15:58:03.757: config mapnik:  plugins_dir=/usr/lib/mapnik/3.1/input
** INFO: 15:58:03.757: config mapnik:  font_dir=/usr/share/fonts
** INFO: 15:58:03.757: config mapnik:  font_dir_recurse=1
** INFO: 15:58:03.758: config renderd(0): Active
** INFO: 15:58:03.758: config renderd(0): unix socketname=/run/renderd/renderd.sock
** INFO: 15:58:03.758: config renderd(0): num_threads=4
** INFO: 15:58:03.758: config renderd(0): tile_dir=/var/cache/renderd/tiles
** INFO: 15:58:03.758: config renderd(0): stats_file=/run/renderd/renderd.stats
** INFO: 15:58:03.758: config map 0:   name(default) file(/home/renderer/src/openstreetmap-carto/mapnik.xml) uri(/tile/) htcp() host(localhost)
** INFO: 15:58:03.758: Initialising unix server socket on /run/renderd/renderd.sock
** INFO: 15:58:03.759: Renderd is using mapnik version 3.1.0
** INFO: 15:58:03.911: Running in foreground mode...
** INFO: 15:58:03.913: Loading parameterization function for 
** INFO: 15:58:03.913: Loading parameterization function for 
** INFO: 15:58:03.913: Loading parameterization function for 
** INFO: 15:58:03.913: Loading parameterization function for 

** (process:323): ERROR **: 15:58:04.982: An error occurred while loading the map layer 'default': file could not be found: '/home/renderer/src/openstreetmap-carto/symbols/quarry.svg' in style 'landcover-low-zoom' in PolygonPatternSymbolizer at line 1668 of '/home/renderer/src/openstreetmap-carto/mapnik.xml'

** (process:323): ERROR **: 15:58:04.990: An error occurred while loading the map layer 'default': file could not be found: '/home/renderer/src/openstreetmap-carto/symbols/quarry.svg' in style 'landcover-low-zoom' in PolygonPatternSymbolizer at line 1668 of '/home/renderer/src/openstreetmap-carto/mapnik.xml'

** (process:323): ERROR **: 15:58:04.991: An error occurred while loading the map layer 'default': file could not be found: '/home/renderer/src/openstreetmap-carto/symbols/quarry.svg' in style 'landcover-low-zoom' in PolygonPatternSymbolizer at line 1668 of '/home/renderer/src/openstreetmap-carto/mapnik.xml'

** (process:323): ERROR **: 15:58:05.039: An error occurred while loading the map layer 'default': file could not be found: '/home/renderer/src/openstreetmap-carto/symbols/quarry.svg' in style 'landcover-low-zoom' in PolygonPatternSymbolizer at line 1668 of '/home/renderer/src/openstreetmap-carto/mapnik.xml'
```

This being the log of my import below, where apparently no problem occurred.

```
error reading input file
+ '[' -e /data/tiles ']'
+ '[' -e /data/style/ ']'
+ '[' -e /data/database/ ']'
++ ls -A /data/style/
+ '[' '!' 'CARTOGRAPHY.md
CHANGELOG.md
CODE_OF_CONDUCT.md
CONTRIBUTING.md
DOCKER.md
Dockerfile
Dockerfile.db
Dockerfile.import
INSTALL.md
LICENSE.txt
README.md
RELEASES.md
USECASES.md
docker-compose.yml
external-data.yml
indexes.sql
indexes.yml
openstreetmap-carto.lua
openstreetmap-carto.style
patterns
preview.png
project.mml
road-colors.yaml
scripts
style
symbols' ']'
+ '[' '!' -f /data/style/mapnik.xml ']'
+ cd /data/style/
+ '[' -f /custom/templated-project.mml ']'
+ cp /custom/templated-project.mml project.mml
+ sed -i 's|{{replace:dbname}}|mapnik|g' project.mml
+ sed -i 's|{{replace:host}}|dpg-postgresql|g' project.mml
+ sed -i 's|{{replace:port}}|5432|g' project.mml
+ sed -i 's|{{replace:user}}|postgres|g' project.mml
+ set +x
+ carto project.mml
+ '[' import == import ']'
+ chown renderer: /data/database/
+ createdb -E UTF8 -O postgres mapnik
+ psql -c 'CREATE EXTENSION IF NOT EXISTS postgis;'
CREATE EXTENSION
+ psql -c 'CREATE EXTENSION IF NOT EXISTS hstore;'
CREATE EXTENSION
+ psql -c 'ALTER TABLE geometry_columns OWNER TO postgres;'
ALTER TABLE
+ psql -c 'ALTER TABLE spatial_ref_sys OWNER TO postgres;'
ALTER TABLE
+ '[' disabled == enabled ']'
+ '[' disabled == 1 ']'
+ '[' -f /data/brazil.poly ']'
+ cp /data/brazil.poly /data/database/brazil.poly
+ chown renderer: /data/database/brazil.poly
+ '[' '' == enabled ']'
+ '[' '' == 1 ']'
+ sudo -u renderer osm2pgsql --database=mapnik --host=dpg-postgresql --port=5432 --user=postgres --password --create --slim -G --hstore --tag-transform-script /data/style/openstreetmap-carto.lua --number-processes 4 -S /data/style/openstreetmap-carto.style /data/brazil-latest.osm.pbf
+ echo
2023-06-26 08:30:53  osm2pgsql version 1.6.0
Password:2023-06-26 08:30:53  Database version: 14.5 (Debian 14.5-2.pgdg110+2)
2023-06-26 08:30:53  PostGIS version: 3.3
2023-06-26 08:30:53  Setting up table 'planet_osm_point'
2023-06-26 08:30:53  Setting up table 'planet_osm_line'
2023-06-26 08:30:53  Setting up table 'planet_osm_polygon'
2023-06-26 08:30:53  Setting up table 'planet_osm_roads'

Processing: Node(170k 170.0k/s) Way(0k 0.00k/s) Relation(0 0.0/s)
Processing: Node(990k 495.0k/s) Way(0k 0.00k/s) Relation(0 0.0/s)
Processing: Node(1510k 503.3k/s) Way(0k 0.00k/s) Relation(0 0.0/s)
.
.
.
.
.
Processing: Node(259799k 137.0k/s) Way(19431k 5.64k/s) Relation(327500 510.1/s)
Processing: Node(259799k 137.0k/s) Way(19431k 5.64k/s) Relation(328270 510.5/s)
                                                                                          
2023-06-26 10:10:41  Reading input files done in 5988s (1h 39m 48s).
2023-06-26 10:10:41    Processed 259799112 nodes in 1896s (31m 36s) - 137k/s
2023-06-26 10:10:41    Processed 19431766 ways in 3445s (57m 25s) - 6k/s
2023-06-26 10:10:41    Processed 328748 relations in 647s (10m 47s) - 508/s
2023-06-26 10:10:43  Clustering table 'planet_osm_roads' by geometry...
2023-06-26 10:10:43  Clustering table 'planet_osm_polygon' by geometry...
2023-06-26 10:10:43  Clustering table 'planet_osm_line' by geometry...
2023-06-26 10:10:43  Clustering table 'planet_osm_point' by geometry...
2023-06-26 10:13:50  Creating geometry index on table 'planet_osm_point'...
2023-06-26 10:14:04  Creating geometry index on table 'planet_osm_roads'...
2023-06-26 10:14:38  Creating osm_id index on table 'planet_osm_roads'...
2023-06-26 10:14:40  Analyzing table 'planet_osm_roads'...
2023-06-26 10:14:41  Done postprocessing on table 'planet_osm_nodes' in 0s
2023-06-26 10:14:41  Building index on table 'planet_osm_ways'
2023-06-26 10:15:52  Creating osm_id index on table 'planet_osm_point'...
2023-06-26 10:16:00  Analyzing table 'planet_osm_point'...
2023-06-26 10:16:01  Building index on table 'planet_osm_rels'
2023-06-26 10:23:55  Creating geometry index on table 'planet_osm_line'...
2023-06-26 10:27:01  Creating geometry index on table 'planet_osm_polygon'...
2023-06-26 10:28:39  Creating osm_id index on table 'planet_osm_line'...
2023-06-26 10:29:00  Analyzing table 'planet_osm_line'...
2023-06-26 10:32:53  Creating osm_id index on table 'planet_osm_polygon'...
2023-06-26 10:33:18  Analyzing table 'planet_osm_polygon'...
2023-06-26 11:08:44  Done postprocessing on table 'planet_osm_ways' in 3243s (54m 3s)
2023-06-26 11:08:44  Done postprocessing on table 'planet_osm_rels' in 20s
2023-06-26 11:08:44  All postprocessing on table 'planet_osm_point' done in 318s (5m 18s).
2023-06-26 11:08:44  All postprocessing on table 'planet_osm_line' done in 1098s (18m 18s).
2023-06-26 11:08:44  All postprocessing on table 'planet_osm_polygon' done in 1356s (22m 36s).
2023-06-26 11:08:44  All postprocessing on table 'planet_osm_roads' done in 238s (3m 58s).
2023-06-26 11:08:44  osm2pgsql took 9471s (2h 37m 51s) overall.

+ '[' -f /nodes/flat_nodes.bin ']'
+ '[' -f /data/style/indexes.sql ']'
+ psql -f /data/style/indexes.sql
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
+ chown -R renderer: /home/renderer/src/ /data/style/
+ '[' -f /data/style/scripts/get-external-data.py ']'
+ '[' -f /data/style/external-data.yml ']'
+ '[' -f /custom/templated-external-data.yml ']'
+ cp /custom/templated-external-data.yml /data/style/external-data.yml
+ sed -i 's|{{replace:dbname}}|mapnik|g' /data/style/external-data.yml
+ sed -i 's|{{replace:host}}|dpg-postgresql|g' /data/style/external-data.yml
+ sed -i 's|{{replace:port}}|5432|g' /data/style/external-data.yml
+ sed -i 's|{{replace:user}}|postgres|g' /data/style/external-data.yml
+ set +x
+ sudo -E -u renderer python3 /data/style/scripts/get-external-data.py -c /data/style/external-data.yml -D /data/style/data
INFO:root:Starting load of external data into database
INFO:root:Checking table simplified_water_polygons
INFO:root:  Fetching /osm-geofabrik/update/mapnik-archives/simplified-water-polygons-split-3857.zip
INFO:root:  Getting local file: simplified-water-polygons-split-3857.zip
INFO:root:  Decompressing file
INFO:root:  Importing into database
INFO:root:  Import complete
INFO:root:Checking table water_polygons
INFO:root:  Fetching /osm-geofabrik/update/mapnik-archives/water-polygons-split-3857.zip
INFO:root:  Getting local file: water-polygons-split-3857.zip
INFO:root:  Decompressing file
INFO:root:  Importing into database
INFO:root:  Import complete
INFO:root:Checking table icesheet_polygons
INFO:root:  Fetching /osm-geofabrik/update/mapnik-archives/antarctica-icesheet-polygons-3857.zip
INFO:root:  Getting local file: antarctica-icesheet-polygons-3857.zip
INFO:root:  Decompressing file
INFO:root:  Importing into database
INFO:root:  Import complete
INFO:root:Checking table icesheet_outlines
INFO:root:  Fetching /osm-geofabrik/update/mapnik-archives/antarctica-icesheet-outlines-3857.zip
INFO:root:  Getting local file: antarctica-icesheet-outlines-3857.zip
INFO:root:  Decompressing file
INFO:root:  Importing into database
INFO:root:  Import complete
INFO:root:Checking table ne_110m_admin_0_boundary_lines_land
INFO:root:  Fetching /osm-geofabrik/update/mapnik-archives/ne_110m_admin_0_boundary_lines_land.zip
INFO:root:  Getting local file: ne_110m_admin_0_boundary_lines_land.zip
INFO:root:  Decompressing file
INFO:root:  Importing into database
INFO:root:  Import complete
+ sudo -u renderer touch /data/database/planet-import-complete
+ exit 0

**Comment by Istador** [comment]
The error message is:
```
** (process:323): ERROR **: 15:58:04.982: An error occurred while loading the map layer 'default': file could not be found: '/home/renderer/src/openstreetmap-carto/symbols/quarry.svg' in style 'landcover-low-zoom' in PolygonPatternSymbolizer at line 1668 of '/home/renderer/src/openstreetmap-carto/mapnik.xml'
```

If I'm not mistaken, you have a volume mount for `/data/style/`. Likely for a custom style? (Because the `ls -A /data/style/` in the `import` is non empty, and for the `run` it contains the `mapnik.xml` that was created by the `import`.)

Make sure that the `/symbols/quarry.svg` file exists in what you mount into the container.

---

I'm not sure where the `error reading input file` message at the beginning is coming from. Likely from your custom modifications as with the `[ -e ... ]` checks?

**Comment by abreza** [comment]
Hello,

I encountered a similar issue and managed to resolve it. Here's how I did it:

1. I manually downloaded the following files:

    - [simplified-water-polygons-split-3857.zip](https://osmdata.openstreetmap.de/download/simplified-water-polygons-split-3857.zip)
    - [water-polygons-split-3857.zip](https://osmdata.openstreetmap.de/download/water-polygons-split-3857.zip)
    - [antarctica-icesheet-polygons-3857.zip](https://osmdata.openstreetmap.de/download/antarctica-icesheet-polygons-3857.zip)
    - [antarctica-icesheet-outlines-3857.zip](https://osmdata.openstreetmap.de/download/antarctica-icesheet-outlines-3857.zip)
    - [ne_110m_admin_0_boundary_lines_land.zip](https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_boundary_lines_land.zip)

2. I ran a Python proxy server to serve these files.

3. I updated the `openstreetmap-carto/external-data.yml` file to use local URLs (http://localhost:8000/file.zip).

4. I updated the Dockerfile to copy the modified `external-data.yml` file into the Docker image. Here's the Dockerfile:

    ```Dockerfile
    FROM overv/openstreetmap-tile-server:latest
    COPY ./external-data.yml /home/renderer/src/openstreetmap-carto-backup/external-data.yml
    EXPOSE 80 5432
    ENTRYPOINT ["/run.sh"]
    ```

5. I built the Docker image using the updated Dockerfile with this command:

    ```bash
    docker build -t overv/openstreetmap-tile-server-localfile:latest .
    ```

6. Finally, I ran the Docker image with the necessary volume mappings:

    ```bash
    docker run \
        -v /home/ubuntu/map_data/example.osm.pbf:/data/region.osm.pbf \
        -v osm-data:/data/database/ \
        overv/openstreetmap-tile-server-localfile:latest \
        import
    ```

I hope this helps!

**Comment by devinfra1** [comment]
Hi @abreza,

Thanks so much for being willing to help!

I managed to solve this problem also in a slightly different way, but thanks for the help!

I made some changes in the python script, responsible for the process of reading and unpacking these mentioned files and then used them locally.

**Comment by SuedaSen** [comment]
> Hello,
> 
> I encountered a similar issue and managed to resolve it. Here's how I did it:
> 
>     1. I manually downloaded the following files:
>        
>        * [simplified-water-polygons-split-3857.zip](https://osmdata.openstreetmap.de/download/simplified-water-polygons-split-3857.zip)
>        * [water-polygons-split-3857.zip](https://osmdata.openstreetmap.de/download/water-polygons-split-3857.zip)
>        * [antarctica-icesheet-polygons-3857.zip](https://osmdata.openstreetmap.de/download/antarctica-icesheet-polygons-3857.zip)
>        * [antarctica-icesheet-outlines-3857.zip](https://osmdata.openstreetmap.de/download/antarctica-icesheet-outlines-3857.zip)
>        * [ne_110m_admin_0_boundary_lines_land.zip](https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_boundary_lines_land.zip)
> 
>     2. I ran a Python proxy server to serve these files.
> 
>     3. I updated the `openstreetmap-carto/external-data.yml` file to use local URLs (http://localhost:8000/file.zip).
> 
>     4. I updated the Dockerfile to copy the modified `external-data.yml` file into the Docker image. Here's the Dockerfile:
>        ```dockerfile
>        FROM overv/openstreetmap-tile-server:latest
>        COPY ./external-data.yml /home/renderer/src/openstreetmap-carto-backup/external-data.yml
>        EXPOSE 80 5432
>        ENTRYPOINT ["/run.sh"]
>        ```
> 
>     5. I built the Docker image using the updated Dockerfile with this command:
>        ```shell
>        docker build -t overv/openstreetmap-tile-server-localfile:latest .
>        ```
> 
>     6. Finally, I ran the Docker image with the necessary volume mappings:
>        ```shell
>        docker run \
>            -v /home/ubuntu/map_data/example.osm.pbf:/data/region.osm.pbf \
>            -v osm-data:/data/database/ \
>            overv/openstreetmap-tile-server-localfile:latest \
>            import
>        ```
> 
> 
> I hope this helps!

Hi @abreza ,
Thanks for your answer, appreciate. 
I wonder about, will it be possible to show 5 zip file without opening a server? I mean is it possible like writing on yaml file:

-     #url: file:///data/ne_110m_admin_0_boundary_lines_land.zip
Something like this?
I don't want to open server, just I want to show url directly.
I did something like this on Dockerfile:
```dockerfile
COPY ./data/antarctica-icesheet-outlines-3857.zip /data/antarctica-icesheet-outlines-3857.zip 
COPY ./data/antarctica-icesheet-polygons-3857.zip /data/antarctica-icesheet-polygons-3857.zip
COPY ./data/ne_110m_admin_0_boundary_lines_land.zip /data/ne_110m_admin_0_boundary_lines_land.zip
COPY ./data/simplified-water-polygons-split-3857.zip /data/simplified-water-polygons-split-3857.zip
COPY ./data/water-polygons-split-3857.zip /data/water-polygons-split-3857.zip

``` 

Any idea for this? I need your opinions guys. If its not possible, can you explain why? Thanks for now.

**Comment by mrtfn** [comment]
> Hello,
> 
> I encountered a similar issue and managed to resolve it. Here's how I did it:
> 
> 1. I manually downloaded the following files:
>    
>    * [simplified-water-polygons-split-3857.zip](https://osmdata.openstreetmap.de/download/simplified-water-polygons-split-3857.zip)
>    * [water-polygons-split-3857.zip](https://osmdata.openstreetmap.de/download/water-polygons-split-3857.zip)
>    * [antarctica-icesheet-polygons-3857.zip](https://osmdata.openstreetmap.de/download/antarctica-icesheet-polygons-3857.zip)
>    * [antarctica-icesheet-outlines-3857.zip](https://osmdata.openstreetmap.de/download/antarctica-icesheet-outlines-3857.zip)
>    * [ne_110m_admin_0_boundary_lines_land.zip](https://naturalearth.s3.amazonaws.com/110m_cultural/ne_110m_admin_0_boundary_lines_land.zip)
> 2. I ran a Python proxy server to serve these files.
> 3. I updated the `openstreetmap-carto/external-data.yml` file to use local URLs (http://localhost:8000/file.zip).
> 4. I updated the Dockerfile to copy the modified `external-data.yml` file into the Docker image. Here's the Dockerfile:
>    FROM overv/openstreetmap-tile-server:latest
>    COPY ./external-data.yml /home/renderer/src/openstreetmap-carto-backup/external-data.yml
>    EXPOSE 80 5432
>    ENTRYPOINT ["/run.sh"]
> 5. I built the Docker image using the updated Dockerfile with this command:
>    docker build -t overv/openstreetmap-tile-server-localfile:latest .
> 6. Finally, I ran the Docker image with the necessary volume mappings:
>    docker run \
>        -v /home/ubuntu/map_data/example.osm.pbf:/data/region.osm.pbf \
>        -v osm-data:/data/database/ \
>        overv/openstreetmap-tile-server-localfile:latest \
>        import
> 
> I hope this helps!

Since I'm a newbie I can confirm this can be a little more noob friendly.
If you want to keep it easy, you can use `python -m http.server 8000` to serve the files for the container but you will see following errors which I'm going to help you make it work.

```bash
...
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
CREATE INDEX
+ chown -R renderer: /home/renderer/src/ /data/style/
+ '[' -f /data/style/scripts/get-external-data.py ']'
+ '[' -f /data/style/external-data.yml ']'
+ sudo -E -u renderer python3 /data/style/scripts/get-external-data.py -c /data/style/external-data.yml -D /data/style/data
INFO:root:Starting load of external data into database
INFO:root:Checking table simplified_water_polygons
INFO:root:  Fetching http://localhost:8000/simplified-water-polygons-split-3857.zip
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 394, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 234, in request
    super(HTTPConnection, self).request(method, url, body=body, headers=headers)
  File "/usr/lib/python3.10/http/client.py", line 1282, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1328, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1277, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "/usr/lib/python3.10/http/client.py", line 1037, in _send_output
    self.send(msg)
  File "/usr/lib/python3.10/http/client.py", line 975, in send
    self.connect()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 200, in connect
    conn = self._new_conn()
  File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7209b5bf26e0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3/dist-packages/urllib3/util/retry.py", line 574, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /simplified-water-polygons-split-3857.zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7209b5bf26e0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/data/style/scripts/get-external-data.py", line 311, in <module>
    main()
  File "/data/style/scripts/get-external-data.py", line 235, in main
    download = s.get(source["url"], headers=headers)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 557, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 544, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3/dist-packages/requests/sessions.py", line 657, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3/dist-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /simplified-water-polygons-split-3857.zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7209b5bf26e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
```

As the errors:
- `ConnectionRefusedError: [Errno 111] Connection refused`
- `urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7209b5bf26e0>: Failed to establish a new connection: [Errno 111] Connection refused`
- `requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=8000): Max retries exceeded with url: /simplified-water-polygons-split-3857.zip (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7209b5bf26e0>: Failed to establish a new connection: [Errno 111] Connection refused'))`

It cannot get access to the URL you put inside the 
[external-data.yml](https://github.com/gravitystorm/openstreetmap-carto/blob/master/external-data.yml)
Because you are running the Python script to host the files on the host machine, the expected behaviour is that you cannot connect to `http://localhost:8000/...` from inside the containers, which is causing this error. 
What you can do on a Windows machine is to just rebuild the image using the correct. accessible from inside the container URLs, which are like this:
```yml
...
url: http://host.docker.internal:8000/simplified-water-polygons-split-3857.zip
...
```

Since replacing `localhost` with `host.docker.internal` will ensure the container knows to look for the files in the host network, not somewhere else.

> [!WARNING]
>  This Method is just for Windows, I think. For Linux, you should expose the port of your host machine to the container or just run the Python HTTP server inside the container, but since you are a Linux user, pretty sure you'll find your way out XD
> Potential Linux Solutions on StackOverflow
> - [From inside of a Docker container, how do I connect to the localhost of the machine? [closed]](https://stackoverflow.com/questions/24319662/from-inside-of-a-docker-container-how-do-i-connect-to-the-localhost-of-the-mach)
> -  [What is the Linux equivalent of "host.docker.internal"? [duplicate]](https://stackoverflow.com/questions/48546124/what-is-the-linux-equivalent-of-host-docker-internal)

**Comment by mvineetmenon** [comment]
> file:///data/ne_110m_admin_0_boundary_lines_land.zip

I tried doing this, but aparently the python requests api doesn't accept `file:///` as protocol and fails there.

> COPY ./data/antarctica-icesheet-outlines-3857.zip /data/antarctica-icesheet-outlines-3857.zip 

This is actually discouraged as you will be making the docker unnecessaily large with data. When I was doing this, I mounted the local directory onto the docker container.
