### ISSUE TITLE
Updating error trim_osc 'list' object has no attribute '__array_interface__' and infinite downloading

### ISSUE THREAD

**Issue by amenk** [Overv/openstreetmap-tile-server#51]
I have built the Docker container on my own yesterday.

During updating I get an error on osm_trim

```
renderer@bffdaac26a5f:~/src/openstreetmap-carto$ /home/renderer/src/regional/trim_osc.py -d gis -p /var/lib/mod_tile/data.poly -z /var/lib/mod_tile/changes.osc.gz /var/lib/mod_tile/changes2.osc.gz
Traceback (most recent call last):
  File "shapely/speedups/_speedups.pyx", line 234, in shapely.speedups._speedups.geos_linearring_from_py
AttributeError: 'list' object has no attribute '__array_interface__'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/renderer/src/regional/trim_osc.py", line 82, in <module>
    tpoly = poly_parse(options.poly)
  File "/home/renderer/src/regional/trim_osc.py", line 42, in poly_parse
    result = Polygon(poly)
  File "/usr/lib/python3/dist-packages/shapely/geometry/polygon.py", line 240, in __init__
    ret = geos_polygon_from_py(shell, holes)
  File "/usr/lib/python3/dist-packages/shapely/geometry/polygon.py", line 494, in geos_polygon_from_py
    ret = geos_linearring_from_py(shell)
  File "shapely/speedups/_speedups.pyx", line 319, in shapely.speedups._speedups.geos_linearring_from_py
TypeError: object of type 'map' has no len()
```

My current workaround is to `apt install python-psycopg2 python-shapely python-lxml` and run osm_trim with python (which is python 2)

There is already an report in the trim_osc repo: https://github.com/Zverik/regional/issues/5

But as this Docker container does not seem to work, we might think about switching to python 2 here?

This is especially problematic because the cron seems to pick up the full diff every time because of this error and creates an unnecessary load on the diff servers

**Comment by Overv** [comment]
I'll update the Dockerfile to run it with Python 2 asap.

**Comment by Zverik** [comment]
This should have been fixed today in https://github.com/Zverik/regional/pull/8, please try again.

**Comment by Overv** [comment]
I've pushed a new Docker image with the region extraction script updated.
